version: "3.7"
services:
  redis:
    image: redis:latest
    environment:
      PASSWORD: "secret"
    ports:
      - 8000:8000
  octaaf:
    image: golang:1.12
    volumes:
      - .:/go/src/octaaf
    working_dir: /go/src/octaaf
    command: go run octaaf -mod vendor
    environment:
      KALICOIN_ENABLED: "true"
      KALICOIN_URI: "http://kalicoin:8000"
      KALICOIN_USERNAME: "octaaf"
      KALICOIN_PASSWORD: "secret"
      JAEGER_AGENT_HOST: "jaeger"
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - octaaf-db
      - jaeger
      - kalicoin

  postgres:
    image: postgres:9.2
    environment:
      POSTGRES_DB: "kalicoin"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    ports:
      - 5432:5432

  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "kali@local.int"
      PGADMIN_DEFAULT_PASSWORD: "kalicoin"
    depends_on:
      - postgres
    ports:
      - 8080:80
  jaeger:
    image: jaegertracing/all-in-one:1.11
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: "9411"
    ports:
      - 6831:6831/udp
      - 16686:16686

